spring.application.name=surveys-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/oceane_surveys
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration SMTP pour l'envoi d'emails
spring.mail.host=smtp.bi.fr
spring.mail.port=587
spring.mail.username=enquetes@oceaneconsulting.com
# Le mot de passe sera injecté par variable d'environnement
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=enquetes@oceaneconsulting.com

# Server Configuration
server.port=8080

# URL de base pour les enquêtes
aws.survey.baseUrl=http://localhost:8080/survey/

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
