# Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/enquetes
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration SMTP pour l'envoi d'emails
spring.mail.host=smtp.bi.fr
spring.mail.port=587
spring.mail.username=enquetes@oceaneconsulting.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=enquetes@oceaneconsulting.com

# URL de base pour les enquêtes
aws.survey.baseUrl=http://51.44.49.25/survey/

# Logging en production
logging.level.root=INFO
logging.level.com.oceane=INFO